# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy to Heroku

on:
  push:
    branches:
      - master  # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Deploy to Heroku
n master      run: |
        heroku login -i
        git remote add heroku https://git.heroku.com/your-heroku-app.git
        git push heroku master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
