name: Deploy to Heroku

on:
  push:
    branches:
      - master  # Or your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Authenticate with Heroku
      run: echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Set Heroku Git Remote
      run: |
        git remote heroku to https://git.heroku.com/python-email-automation.git

    - name: Deploy to Heroku
      run: git push heroku master
